# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-10 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Orginization',
            new_name='Organization',
        ),
    ]
