# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-14 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_auto_20180510_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='End',
            new_name='EndDate',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Start',
            new_name='EndTime',
        ),
        migrations.AddField(
            model_name='article',
            name='StartDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='article',
            name='StartTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
